const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'
const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
const SELECTED_CATEGORY = 'SELECTED_CATEGORY'
const UNSELECTED_CATEGORY = 'SELECTED_CATEGORY'

export {
  FETCH_DATA_ERROR,
  FETCH_DATA_REQUEST,
  FETCH_DATA_SUCCESS,
  SELECTED_CATEGORY,
  UNSELECTED_CATEGORY,
}
